# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='robject',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='robject',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='robject',
            name='project',
        ),
        migrations.DeleteModel(
            name='Robject',
        ),
    ]
